(defun first   (lst) (car lst))
(defun second  (lst) (car (cdr lst)))
(defun third   (lst) (car (nthcdr 2 lst)))
(defun fourth  (lst) (car (nthcdr 3 lst)))
(defun fifth   (lst) (car (nthcdr 4 lst)))
(defun sixth   (lst) (car (nthcdr 5 lst)))
(defun seventh (lst) (car (nthcdr 6 lst)))
(defun eighth  (lst) (car (nthcdr 7 lst)))
(defun ninth   (lst) (car (nthcdr 8 lst)))
(defun tenth   (lst) (car (nthcdr 9 lst)))

(defun rest (lst) (cdr lst))
(defun nth (n lst) (car (nthcdr n lst)))
(defun last (lst)
  (if (null (cdr lst))
      (car lst)
      (last (cdr lst))))
