name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v29

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-cache-${{ runner.os }}-${{ hashFiles('**/*.nix', 'flake.lock') }}
          purge: true

      - name: Set up devShell
        run: nix develop

      - name: Nix build
        run: nix build

      - name: Run spec tests
        run: |
          nix develop --command cabal update
          nix develop --command cabal test
